### ISSUE TITLE
csu commands not terminating on completion

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#1056]
They're left hanging rather than returning to the prompt. Seems to only be an issue on osx.

![screen shot 2018-09-08 at 1 04 29 pm](https://user-images.githubusercontent.com/6937219/45248637-c43aee80-b367-11e8-8d62-6d450fdf5e3d.png)

**Comment by JackMorganNZ** [comment]
Does this occur with all commands?

**Comment by hayleyavw** [comment]
nope, just some.

**Comment by JackMorganNZ** [comment]
Can you let me know the results of:

- `start`
- `end`
- `help`
