### ISSUE TITLE
Support for French contents

### ISSUE THREAD

**Issue by bcopy** [uccser/cs-unplugged#1128]
## Description

I see that the book has already been translated to French (https://interstices.info/wp-content/uploads/2018/01/csunplugged2014-fr-comp.pdf) ; but what about an online French version of csunplugged.org ?

Could the book translation be turned into a push request and added to Github ?

Alternatively, would it be useful to translate 
https://github.com/uccser/cs-unplugged/tree/develop/csunplugged/resources/content/en
into a FRench translation and submit it as a push request ?

What other parts would be required for a french version ?
I expect perhaps the django messages (https://github.com/uccser/cs-unplugged/blob/develop/csunplugged/locale/en/LC_MESSAGES/django.po) but what else ?

**Comment by JackMorganNZ** [comment]
Hi @bcopy, translating into French would be great, and we have aimed to make this as easy as possible using Crowdin for translations: https://crowdin.com/project/cs-unplugged

You can submit translations on that website for French, and we can get these checked and then merged into the website. The files marked as 'High priority' should be translated first as these are required to allow the website to function in French, and then you can pick which other pages of the website can be available in French.

You might see there is already other people who have suggested translations for some strings. Feel free to either suggestion a new translation if you think you can do better, or vote up a good suggested translation.

**Comment by JackMorganNZ** [comment]
Hi @bcopy, I'm going to close this issue since I believe the question has been answered. If you have any more question, please ask them and we will do our best to help. Thanks.
