### ISSUE TITLE
Binary alphabet teacher answer sheet

### ISSUE THREAD

**Issue by taskmaker1** [uccser/cs-unplugged#1149]
Original message from twitter.
Do you have the Binary alphabet teacher answer sheet? The ones I found online have 8 bits, I want 6 as that what all the CSU resources has for the activities. The teacher answer sheet isn't online like it says it is...

Refers to this page
https://csunplugged.org/en/topics/binary-numbers/unit-plan/codes-for-letters-using-binary-representation-junior/#codes-for-letters-using-binary-representation-junior

It is rather hidden the teacher sheet. Could it be made more explicit that the answer is available?

### Checklist

- [x ] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

**Comment by JackMorganNZ** [comment]
Closing as addressed in earlier update.
