### ISSUE TITLE
Add KidBots Unit Plan

### ISSUE THREAD

**Issue by tah942** [uccser/cs-unplugged#139]
## Description

Clearly and concisely describe the issue or suggestion here:

This unit is currently being worked on in google docs. No content to update at the time of writing this issue.

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] The platform(s)/software you are encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Closing this issue as its progress is now managed on internal resource.
