### ISSUE TITLE
Add a webpage for curriculum guides

### ISSUE THREAD

**Issue by tah942** [uccser/cs-unplugged#143]
## Description

Clearly and concisely describe the issue or suggestion here:

The curriculum guide pages will be hardcoded for each curriculum. We don't need to store related Digital Technology Curriculum Strands in the database because each curriculum will have their own webpages to then link the unit plans, lessons, curriculum integration into (where appropriate) 

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

**Comment by JackMorganNZ** [comment]
Closing this issue as its progress is now managed on internal resource.
