### ISSUE TITLE
Make application for viewing all data in local development

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#151]
This is to cover content that is added that doesn't actually have a link to it yet (e.g. programming exercises for a topic that has not yet been created).

**Comment by JackMorganNZ** [comment]
Move existing templates (like page for programming exercise difficulties) to the new ``__dev_view__`` app.

**Comment by hayleyavw** [comment]
- Play with making mock topic/unit plan
- Show lessons/unit plans not attached to topic
