### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID for classic cite

### ISSUE THREAD

**Issue by BitsAndBytesTeacher** [uccser/cs-unplugged#1648]
## Description

Clearly and concisely describe the issue or suggestion here:
There is a mismatch with the domain name for the classic site. When I navigate to https://classic.csunplugged.org/, I receive the NET::ERR_CERT_COMMON_NAME_INVALID error and cannot access the site. I am using Chrome, but the error is reproducible in Edge.
I am a teacher and need to print content from this website on 20 September 2021. Thank you for the quick response.
![image](https://user-images.githubusercontent.com/91013392/133926789-96c3d6cd-c34e-4568-a40d-801bbaea9541.png)

### Checklist

*Change the space in the box to an `x` for those you have completed. You can also fill these out after creating the issue.*

- [X] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).

If this is a code related issue, please include the following in your description:

- [X] Steps to reproduce the behavior
- [X] The platform(s)/software you are encountering the issue on
- [X] The behavior you expect to see, and the actual behavior

**Comment by JackMorganNZ** [comment]
Hi @BitsAndBytesTeacher, we have solved this issue a few hours ago however our classic website is currently down due to a urgent server migration. However if you send me an email at jack.morgan@canterbury.ac.nz, I can send you the resource you are looking for.
