### ISSUE TITLE
Review added content

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#217]
The content that has been added for binary numbers and error detection and correction will need to be proof read.

- [ ] curriculum areas

Binary numbers:
- [ ] topic description
- [ ] unit plan
- [ ] other resources
- [ ] lesson 1
- [ ] lesson 2
- [ ] lesson 3
- [ ] binary art
- [ ] binary name necklaces
- [ ] binary or normal candles
- [ ] binary patterns
- [ ] binary tunes
- [ ] biographies and binary number system history
- [ ] whose cake is it

Error Detection and Correction:

- [ ] topic description
- [ ] unit plan
- [ ] other resources
- [ ] lesson 1
- [ ] lesson 2

**Comment by JackMorganNZ** [comment]
Split into separate issues.
