### ISSUE TITLE
Resource Form Page interface updates

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#355]
- ~"Local Generation Only" - if this is going in the production version, then we should come up with a different title because to a teacher this probably wont mean much~
- [x] "Generate Resource" button needs styling to match the rest of the site

**Comment by JackMorganNZ** [comment]
Regarding the top one, see this part of the template:
```html
    {% if debug %}
      <hr>
      <h3>Local Generation Only</h3>

      <fieldset>
        <legend>Header Text</legend>
        <input type="text" name="header_text" placeholder="Example School: Room Four" class="long-text-field">
      </fieldset>

      {% if resource.copies %}
        <fieldset>
          <legend>Number of Copies</legend>
          <input type="number" name="copies" value=1 min=1 max=50>
        </fieldset>
      {% endif %}

      <hr>
      <input type="submit" value="Generate Resource" class="mb-3" />
    {% else %}
      {% if resource.copies %}
      <div class="alert alert-info" role="alert">
        The download of this resource includes 30 unique copies.
      </div>
      {% endif %}

      <input type="submit" value="Download Resource" class="mb-3"/>
    {% endif %}
```

If it is local (i.e. `debug`), then it displays the local generation header text, displays the copies option, and a button with 'Generate'.

If it's production, then it displays alert stating it's 30 copies (if the resource allows copies), and a button with 'Download'.

Is this what you were implying?

**Comment by JackMorganNZ** [comment]
Have removed the first item as it was already solved.
