### ISSUE TITLE
Binary Numbers Icon needs transparent background

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#357]
Can see a white background behind the binary numbers icon on the Topics page when hovered over, this should instead be transparent.

**Comment by saranglove** [comment]
https://drive.google.com/open?id=0B-SN1PgPBbCYSVp2U1cxbFc2bGs

**Comment by JackMorganNZ** [comment]
Could we please get an image closer to the size it would be used, as this is ~200kb for quite a small image. The existing image was 446x272, so a new image at roughly 500 pixels wide would be great.

**Comment by saranglove** [comment]
https://drive.google.com/open?id=0B-SN1PgPBbCYM1pESTFLUmxGc1E
