### ISSUE TITLE
Fix issues from updating binary number programming exercises

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#359]
These issues occurred when updating binary number programming exercises in #340.

- [x] 1.5 has the learning outcome:
   > Explain why a join block is required to combine different data types (variables, text, equations).

    There is no learning outcome with this text, should this learning outcome be added or skipped?

- [x] 2.2 has the learning outcome:
   > Explain why a join block is required to combine different data types (variables, text, equations).

    There is no learning outcome with this text, should this learning outcome be added or skipped?

- [ ] 4.5 has the learning outcome:
   > Prove how indexing to access a letter at the specified position in a string works

    There is no learning outcome with this text, should this learning outcome be added or skipped?

- [x] 5.1 has the following text within Scratch hints:
   > In the extra challenge you need to ask the user to enter a number less than or equal to 31 if the input which was entered was greater than 31.

   This question does not have an extra challenge so the sentence was removed. This needs confirmation this was the right action.

- [ ] 7.3 and 7.4 are considered as alternative exercises, but the name are not consistent.

- [x] 9.1 has a ridiculous amount of content and options. I did not list recommended blocks for each type, as there would be too many. It may be worth considering only showing one way, and mentioning other approaches.

**Comment by tah942** [comment]
1.5 add: programming-explain-join-concatenate
2.2 add: programming-explain-join-concatenate
4.5 add: programming-prove-indexing (Jack a side note, the verb changed from prove to demonstrate in the text, so do we make a new learning outcome with a new slug to match?)
5.1 Yes (it was the right action)
7.2 and 7.3 I'm happy with the titles. No action required.
9.1 Looks good on the screen. No action required.
