### ISSUE TITLE
Review binary numbers programming exercises

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#363]
This involves checking all binary numbers programming exercises (after #361 has been merged) to check their:

- Name
- Challenge level
- Learning outcomes
- Description
- Expected values
- Hints
- Solution

It would be quite easy for a mistake to slip through when inserting this content, so a thorough checking is required (in particular making sure the embedded iframes are the correct).

Created after splitting #217.

**Comment by JackMorganNZ** [comment]
The wording of 'display the number for 1 second' should be removed from any generic descriptions.

**Comment by tah942** [comment]
1.1 Replace the text in testing examples from There are no testing examples for this challenge. To: The output will always show the numbers 1, 2, 4, 8 and 16 (there is no input).

7.2 Remove the word positive from the title. 

8.2 Remove the word positive from the title.

9.1 Solution 1: relabel Blocks for cat sprite to read as blocks for cat sprite (labelled binary number) 
9.1 Solution 2: relabel Blocks for cat sprite to read as blocks for cat sprite (labelled binary number) 
9.1 Solution 3: relabel Blocks for cat sprite to read as blocks for cat sprite (labelled binary number)
