### ISSUE TITLE
Review binary numbers curriculum integrations

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#366]
This involves checking all binary numbers curriculum integrations to check their:

- Name
- Curriculum areas
- Description
- Prerequisite lessons (if applicable)

Created after splitting #217.

**Comment by tah942** [comment]
On the curriculum integrations > binary art > link the pre-requisite lesson to be: https://cs-unplugged.appspot.com/en/topics/binary-numbers/unit-plan/codes-for-letters-using-binary-representation/
