### ISSUE TITLE
Update CT decomposition icon to be easier to see 

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#374]
Currently the colour used for this icon is quite bright, a darker/more golden yellow would help increase the contrast when viewing.

![pasted image at 2017_05_25 07_11 pm](https://cloud.githubusercontent.com/assets/8001048/26470633/89b2e3ae-41f2-11e7-81ff-7500d3b1fc84.png)

Result of work from #373.

**Comment by saranglove** [comment]
https://drive.google.com/open?id=0B-SN1PgPBbCYMzF3MmN2cGIwQzQ

how does this work?

**Comment by JackMorganNZ** [comment]
I've added the new image here:
![image](https://cloud.githubusercontent.com/assets/8001048/26476227/6d3723f6-4211-11e7-91c6-b63cd2e82f7c.png)

I've darkened the text by 10% of the logo colour to make it easier to read.
