### ISSUE TITLE
Investigate hosting options

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#38]
Investigate possible hosting options, including:

- Google Cloud Platform
- Microsoft Azure
- Webfaction
- etc

Need to check for:
- Ease of use
- Ease of scaling
- Price
- Performance

**Comment by JackMorganNZ** [comment]
I recommend reading chapters 30 and 31 of Two Scoops of Django 1.8.

**Comment by hayleyavw** [comment]
We are going to go with Google Cloud Platform.
