### ISSUE TITLE
Sorting Network Lesson 1 (8 - 10) is missing learning outcomes

### ISSUE THREAD

**Issue by tah942** [uccser/cs-unplugged#418]
Sorting Network Lesson 1 (8- 10) is missing learning outcomes and need to be written.

#412

**Comment by tah942** [comment]
Please add: 
Sorting-explain-parallel-algorithm
Sorting-use-selection-sort
Sorting-identify-number-range
Sorting-organise-objects-size

**Comment by JackMorganNZ** [comment]
This has been implemented at some point.
