### ISSUE TITLE
Error Correction and Detection Lesson 2 (8 - 10) is missing learning outcomes

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#419]

**Comment by tah942** [comment]
The following learning outcomes are to be added to this lesson

error-explain-steps-12-productcode-checksum
error-discuss-checksum-algorithm-12-13-productcode
error-explain-checksum-reliable
numeracy-explain-modulo
numeracy-identify-modulo-everyday-life
