### ISSUE TITLE
Updating the information in Binary Unit and lessons relating to decimal numbers

### ISSUE THREAD

**Issue by tah942** [uccser/cs-unplugged#422]
Write a clear definition of what we refer to for decimal/base 10/Whole Numbers that doesn't confuse teachers that they think it's a number like 0.25.  

#132
#133
#134

**Comment by tah942** [comment]
In CS Unplugged we use the term decimal number to represent all natural numbers. There are many different phrases for these numbers including whole numbers, counting in base 10, cardinal numbers and ordinal numbers.  Examples of these numbers are 7, 41, 1052.

**Comment by JackMorganNZ** [comment]
Updated text:

> In CS Unplugged we use the term *decimal number* to represent all whole numbers. There are many different phrases for these numbers including whole numbers, counting in base 10, cardinal numbers and ordinal numbers. Examples of these numbers are 7, 41, 1052.

**Comment by JackMorganNZ** [comment]
Closed in 3d918db
