### ISSUE TITLE
Change lesson ages to be min and max instead of list of numbers

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#44]
This will make the `Age` model irrelevant, as the two values can be stored as integers.

**Comment by hayleyavw** [comment]
When we chatted about this yesterday, you were pretty adamant that the model would not be removed, what changed?

**Comment by JackMorganNZ** [comment]
I'm pretty sure we came to the conclusion that the `Age` model was un-needed.

It would only be useful if you want to see all lessons for an age, but we can still perform that query directly on the `Lesson` model.
