### ISSUE TITLE
Fix the text between $ sign turned into math expression

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#461]
## Description

Somehow need to fix the sentence ("20 for the product...") in between two $ signs that have been turned into a math expression. Needs to be plain text. In http://cs-unplugged-develop.appspot.com/en-gb/topics/error-detection-and-correction/unit-plan/#real-world-implications

![image](https://user-images.githubusercontent.com/20089275/27208880-93288cf8-529c-11e7-81ee-d5729b8ee937.png)

**Comment by JackMorganNZ** [comment]
@ravenmaster001 I think the best option is to avoid the single dollar sign delimiter (see https://github.com/mitya57/python-markdown-math#math-delimiters). Thoughts?

**Comment by ravenmaster001** [comment]
@JackMorganNZ looks like the single dollar sign should be disabled by default. I would agree with disabling this then double dollar signs would be best then when math is necessary.
