### ISSUE TITLE
Process Kordac conversion result data

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#48]
When a Kordac conversion takes place, the load script should:

- Check images found are within static folder.
- Check glossary entries are defined in the database.
- Generate any required images (scratch images to be added in future Kordac release).

**Comment by hayleyavw** [comment]
@JackMorganNZ you've done the third bullet point here haven't you?

**Comment by JackMorganNZ** [comment]
Yep, three point is done (though with known issue #72).
