### ISSUE TITLE
Missing videos in the Searching Algorithms unit plan

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/cs-unplugged#561]
Missing videos and text from Unit Plan (https://docs.google.com/document/d/14Exafr-nE7s4yDuvPMn-zv81gVvK5HMS8Unu-wRW2BI/edit)

> These videos are being scheduled to be worked on. 
> Video 1: Sequential search: Random numbered cards with pictures on them. (using numbers from 0 - 31) - SETTING: As if it’s a maths group in a class setting
>
> Video 2: Binary search using numbered cards with pictures on them ranging from 0 - 999. 
>
> Video 3: Linking the “Treasure Hunt” activities to statistics

**Comment by tah942** [comment]
These are yet to be made, so please remove the text from the unit plan (if you haven't already) and we'll make these in the next round of videoing which is likely to be in September.
