### ISSUE TITLE
Check if env is required for Travis

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#574]
Check if the following is still required for Travis CI:

```
env:
  - DOCKER_COMPOSE_VERSION=1.11.2
```

**Comment by ravenmaster001** [comment]
@JackMorganNZ 
Looking at:
- https://docs.travis-ci.com/user/reference/trusty/#Docker
- https://docs.travis-ci.com/user/docker/

That env is not required, unless we are installing our own version of docker-compose.

**Comment by JackMorganNZ** [comment]
Fixed in #915
