### ISSUE TITLE
Possibly use RGB for programming levels?

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#6]
For the three tiers of programming exercises, use RGB to define each tier.

R = Beginner Exercises
G = Intermediate Exercises
B = Challenging Exercises

**Comment by timbellnz** [comment]
I had a discussion with someone where we realised that red is usually the hardest level, so how about:
B = Beginner Exercises
G = Intermediate Exercises
R = Challenging Exercises

**Comment by JackMorganNZ** [comment]
Bonus points if we can get each level to start with the colour's letter.

B = Beginner
G = ?
R = ?

**Comment by tah942** [comment]
B - beginner
G - growing experience
R - ready to expand
