### ISSUE TITLE
Multiple instructions sheets for Treasure Hunt Resource.

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#608]
**Issue: When downloading the treasure hunt resource with instructions, there is an instruction page every second page.**

Currently, the Treasure Hunt resource puts an instruction page in between each of the actual activity sheet.
This is an issue because we don't need that many instruction sheets and it would just waste paper for the teachers to print off all those extra instruction sheets.
This can be fixed by only having one instruction sheet at the beginning of the resource. If the teacher needs more instruction sheets, s/he can just print/photocopy multiple copies them separately.

Currently:
![image](https://user-images.githubusercontent.com/20089275/31419148-9f0d3158-ae96-11e7-8f6c-fb9f3754c074.png)

How it should be fixed:
![image](https://user-images.githubusercontent.com/20089275/31419213-f5d4aa2a-ae96-11e7-955a-0c43e39093fb.png)

**Comment by JackMorganNZ** [comment]
@tah942 is investigating what is best in a classroom environment, either:
- One sheet only
- One sheet per student

**Comment by JackMorganNZ** [comment]
This has been fixed in 4.1.0 as instructions are now written on every sheet.
