### ISSUE TITLE
Mega Issue: Job Badges (Translations & Lines)

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#661]
https://cs-unplugged.appspot.com/en-gb/resources/job-badges/

**Issue 1: The English instructions should be blank to allow for translations.**
**Issue 2: Dotted lines should be solid.**

---
**Issue 1**
Currently, there are English words and instructions statically embedded in the PDF.
This is an issue because you cannot replace the English instructions with other translations.
This can be fixed by leaving the English out of the PDF, leaving the space blank, and then adding translations including English onto the PDF dynamically.

Current:
![image](https://user-images.githubusercontent.com/20089275/32254329-ee1ad682-bf04-11e7-8143-24c7668b265a.png)

To fix:
![image](https://user-images.githubusercontent.com/20089275/32254360-2c1325e8-bf05-11e7-9430-9f1b9efa4955.png)

---
**Issue 2**
Currently, the borders of the badges are dotted/dashed.
This is an issue because dotted/dashed lines are generally recognized to mean fold, not cut.
This can be fixed by changing the dotted/dashed lines into solid lines.

Current:
![image](https://user-images.githubusercontent.com/20089275/32254443-a8d0296e-bf05-11e7-8dcf-deb6405fa237.png)

To fix:
![image](https://user-images.githubusercontent.com/20089275/32254564-6118a99c-bf06-11e7-861e-41b530421217.png)

**Comment by JackMorganNZ** [comment]
This shouldn't be closed until #759 is merged in :smile:

**Comment by saranglove** [comment]
My bad.
