### ISSUE TITLE
Vertically long images are too small in various lessons/UP

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#684]
**Issue: The max-height for images are 18em which makes vertically long illustrations too small on the webpage.**

Currently, vertically long images are too small to view/read on a webpage due to the max-height property being set at 18em.
This is an issue because it is hard to view the image which makes it difficult to understand what the image is trying to portray.
This may require more discussions to be fixed.

Current example from https://cs-unplugged.appspot.com/en-gb/topics/searching-algorithms/sequential-and-binary-search-unit-plan/:
![image](https://user-images.githubusercontent.com/20089275/32806521-a6ab6aa8-c9f1-11e7-9b82-294f74b1b794.png)

**Comment by JackMorganNZ** [comment]
After much research, I think I've come up with a strategy for this problem and varying related issues. The following summary should cover the issues and solutions.

# Problem 1: Sizing

Images within the `static` folder are of various sizes, however depending on the usage and screen size images will want to be displayed at different sizes. For example, some images (like the one in the issue description) should be displayed at full size for all screen sizes, but other images should show at a maximum size (for example: 200 pixels wide).

Images should also be shown as a new block, or floating to the left or right with text wrapped around it.

# Problem 2: Compression

Displaying a large image (for example: 2000 pixels wide) on a phone (for example: 400 pixels wide) is a waste of bandwidth for the user. User's browsers ideally would download an image suitable for their device.

# Solution

Add the `npm` package `gulp-responsive` (https://www.npmjs.com/package/gulp-responsive) to create extra copies of images at varying sizes (including a copy with it's original file name). The package also compresses the image, however there is an issue where some PNG images are larger than the original even when a smaller size, see https://github.com/mahnunchik/gulp-responsive/issues/34. Images could be generated to useful sizes (100, 200, 300, etc pixels) and also close to responsive breakpoints (https://getbootstrap.com/docs/4.0/layout/grid/#customizing-the-grid) however the breakpoints don't take account for the image width (for example, an image might be displayed 50% wide in the container).

The Verto package will need to be updated to allow extra control over the output of the image tags (http://verto.readthedocs.io/en/latest/processors/image.html). The filename should be split to allow adding a suffix to the filename before the extension, and also detect if a width suffix is present. This may or not need a new image relative link tag (this could be embedded in the HTML template).

Once these changes are made, authors will be able to include images in one of three approaches:

- Include an image by it's filename (for example: `apple.png`)
- Include an image by it's filename with a specific width suffix (for example: `apple@200px.png`)

When an image is included by it's filename without a width suffix, the HTML template will include an image with a `srcset` (and possibly `sizes`) attribute to display different images depending on the device width (https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

If an image is included with a specific width, then the `srcset` will not be given.
