### ISSUE TITLE
Fix migration handling on travis

### ISSUE THREAD

**Issue by jordangriffiths01** [uccser/cs-unplugged#694]
Unit tests should run without migrations, with the the test database schema being determined entirely from the current state of the model files and the test settings.

Since merging #643 this has happened locally, but the tests running on Travis still build the schema using the migrations files. This causes issues when the current production database schema differs from that required for the unit tests (specifically, this is occurring for unit tests that test internationalisation features, when the production database only contains columns for English values). This actually should have prevented merging of #680, except ironically that branch was missing a migration file that removed old `de` and `fr` columns (created during feature development) from the database, and so they _were_ available to the unit tests. I won't be able to add that migration until this issue is resolved, as all i18n unit tests will fail until they are allowed to run without migrations.

Production database migrations should _still_ be tested - this basically requires booting the system and then running `./csu update` to check that everything loads correctly with no errors, essentially a dry run of the database update step in the deployment phase. 

Currently this actually happens at the start of _every_ travis job as part of the `./csu start` command. This seems overkill to me, and adds a massive overhead to each job needing to generate all thumbnails etc before actually running any tests. Instead, I'd suggest we refactor the csu script to separate out the 2 distinct phases that currently are both run as part of `./csu start`:
- Starting the docker containers (IMO, should be the only function of `./csu start`)
- Loading database content and other tasks such as static file handling, thumbnail generation etc. (`./csu update`, run from `./csu start`)

I propose the following changes:
- Remove the `./csu update` call from `./csu start`.
- Run all unit tests without migrations (both on travis and locally)
- Add a new travis job to run `./csu update` after `./csu start`, acting as a dry run of the database update step from deployment
- Add missing topics migration file to remove erroneous `de`/`fr` columns

Thoughts @JackMorganNZ @hayleyavw?

**Comment by JackMorganNZ** [comment]
Yes
