### ISSUE TITLE
Footer interface redesign

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#695]
Current footer:
![image](https://user-images.githubusercontent.com/20089275/33109817-91c22f48-cfa8-11e7-9fbd-2d07822969ab.png)

Proposed new redesign:
![image](https://user-images.githubusercontent.com/20089275/33109834-ad010374-cfa8-11e7-99f0-ac221da7d909.png)

**Fonts are subject to change

**Comment by JackMorganNZ** [comment]
This was fixed in #707
