### ISSUE TITLE
Landing page interface redesign

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#698]
Current:
https://cs-unplugged-dev.appspot.com/en/

Proposed new design:
![a thing](https://user-images.githubusercontent.com/20089275/33110427-b2db51ec-cfac-11e7-845b-de9ad6a4c304.png)

**Redesign based on older current landing page.

The main changes are the jumbotron banner, nav bar and footer ( issue #695 )

**Comment by saranglove** [comment]
![artboard 1](https://user-images.githubusercontent.com/20089275/33815585-78ec6562-de97-11e7-89eb-fe7655938de4.png)
![artboard 2](https://user-images.githubusercontent.com/20089275/33815586-79181a5e-de97-11e7-8478-1fa54335b6cc.png)

**Comment by JackMorganNZ** [comment]
Reopening as not completed (accidentally wrote 'fixes' on earlier commit).
