### ISSUE TITLE
Update flow charts in author/topics documentation page

### ISSUE THREAD

**Issue by jordangriffiths01** [uccser/cs-unplugged#749]
Changes made while implementing #612 and #613 mean that the content file/directory structure has changed, as have some small details in the process for adding new content.

These changes are documented in #748, but the flow charts still need to be updated - it is probably much quicker for the original author (@JackMorganNZ) to do this than for me to.

**Comment by caitlind** [comment]
[Pull request submitted for review](https://github.com/uccser/cs-unplugged/pull/1247)
