### ISSUE TITLE
Replace Resources with Printouts on Landing Page and Nav Bar and everywhere else

### ISSUE THREAD

**Issue by saranglove** [uccser/cs-unplugged#765]
![image](https://user-images.githubusercontent.com/20089275/34085255-abf8c3a0-e3f2-11e7-8980-4bff0afc9587.png)

Also everywhere else on the website that says Resources should say Printouts. (Unless talking about Resources in a different context).

**Lazy issue because hayfever has glued my eyes together.

**Comment by JackMorganNZ** [comment]
Fixed in b23aea780fdc403b6885c17827fd0ceff8f37d7b
