### ISSUE TITLE
Store custom Kordac templates

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#77]
The custom Kordac templates for Markdown conversion need to be stored within the repository.
Gut instinct is to store these within the `templates` directory under `markdown_templates` and then exclude this folder from the Django template loader (to avoid loading unused templates in serving webpages).

These can then be loaded for Kordac (possibly a Django loader would do the job).

**Comment by hayleyavw** [comment]
Would have to change settings file (?) to make sure it doesn't traverse the `markdown_templates` folder.
