### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#889]
- Use the new `gtag.js` tracking.
- Track printable downloads.

**Comment by courtneycb** [comment]
I have created an account on Google Tag Manager and added a container for CS Unplugged on there. 
Inside this container I have set up a tag to track PDF downloads using both GA and GTM, however I cannot test it until the GTM snippet has been added to the website. Will make a PR to add this snippet.

**Comment by courtneycb** [comment]
Can we use Google Tag Manager instead?

**Comment by courtneycb** [comment]
We should consider adding an [IP address filter](https://support.google.com/analytics/answer/1034840?hl=en) to exclude internal traffic.

**Comment by courtneycb** [comment]
Google Tag Manager snippet added in #1435. Tags to track Printable downloads and Page views published in GTM and tested. You can view the version of GTM published with the admin account [here](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/versions/accounts/6001848934/containers/32212070/versions/1).
