### ISSUE TITLE
Fix modulo error in The Modulo operator Unplugged lesson

### ISSUE THREAD

**Issue by k-alkiek** [uccser/cs-unplugged#925]
## Description

In [The Modulo operator Unplugged](https://csunplugged.org/en/topics/kidbots/unit-plan/modulo/#lesson-activities) lesson in section "Time to rewind" there is an example that says -8 mod 10 equals 4 which is not true because -8 mod 10 equals 2.

**Comment by JackMorganNZ** [comment]
Thanks @k-alkiek, I've fixed this in the source code and will push out an update in the next week or two.
