### ISSUE TITLE
 Support for Hindi Language.

### ISSUE THREAD

**Issue by vikaskyadav** [uccser/cs-unplugged#982]
## Description

Hey There. Great work. I would like to contribute so that we can have support for students whose native language is not English. Would like the platform to be polyglot supported. I will be contributing actively for support for Hindi Language.

**Comment by JackMorganNZ** [comment]
Sorry for missing your message for months @vikaskyadav! You can contribute translations for Hindi on our translation website: https://crowdin.com/project/cs-unplugged

Thanks, Jack.
